- type: rank
  parent: RMCBaseRankLanceCorporal
  id: RMCRankMaintTechLanceCorporal
  requirements:
  - !type:RoleTimeRequirement
    role: CMJobMaintTech
    time: 252000 # 70 hours

- type: rank
  parent: RMCBaseRankPrivateFirstClass
  id: RMCRankMaintTechPrivateFirstClass
  requirements:
  - !type:RoleTimeRequirement
    role: CMJobMaintTech
    time: 36000 # 10 hours
