# - type: job
  # id: fireteamleader
  # name: job-name-fireteamleader
  # description: job-description-fireteamleader
  # playTimeTracker: jobfireteamleader
  # requirements:
    # - !type:DepartmentTimeRequirement
      # department: Marine
      # time: 28800 #8 hrs
  # startingGear: fireteamleadergear
  # icon: "JobIconSecurityOfficer"
  # supervisors: job-supervisors-squadleader
  # canBeAntag: false
  # access:
  # - Security
  # - Brig
  # - Maintenance
  # - Service
  # - External
  
- type: job
  id: alphafireteamleader
  name: job-name-alpha-fireteamleader
  description: job-description-fireteamleader
  playTimeTracker: jobfireteamleader
  requirements:
    - !type:DepartmentTimeRequirement
      department: Marine
      time: 28800 #8 hrs
  startingGear: fireteamleadergear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-squadleader
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  
- type: job
  id: bravofireteamleader
  name: job-name-bravo-fireteamleader
  description: job-description-fireteamleader
  playTimeTracker: jobfireteamleader
  requirements:
    - !type:DepartmentTimeRequirement
      department: Marine
      time: 28800 #8 hrs
  startingGear: fireteamleadergear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-squadleader
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  
- type: job
  id: charliefireteamleader
  name: job-name-charlie-fireteamleader
  description: job-description-fireteamleader
  playTimeTracker: jobfireteamleader
  requirements:
    - !type:DepartmentTimeRequirement
      department: Marine
      time: 28800 #8 hrs
  startingGear: fireteamleadergear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-squadleader
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  
- type: job
  id: deltafireteamleader
  name: job-name-delta-fireteamleader
  description: job-description-fireteamleader
  playTimeTracker: jobfireteamleader
  requirements:
    - !type:DepartmentTimeRequirement
      department: Marine
      time: 28800 #8 hrs
  startingGear: fireteamleadergear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-squadleader
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External

- type: startingGear
  id: fireteamleadergear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSec
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHelmetBasic
    outerClothing: ClothingOuterArmorBasic
    id: SecurityPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolMk58Nonlethal
  innerclothingskirt: ClothingUniformJumpskirtSec
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
