- type: job
  id: hospitalcorpsman
  name: job-name-hospitalcorpsman
  description: job-description-hospitalcorpsman
  playTimeTracker: hospitalcorpsman
  requirements:
    - !type:DepartmentTimeRequirement
      department: Marine
      time: 3600 #1 hrs
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 3600 #1 hrs
  startingGear: BrigmedicGear
  icon: "JobIconBrigmedic"
  supervisors: job-supervisors-squadleader
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  
- type: entity
  noSpawn: true
  parent: ClothingBackpackBrigmedic
  id: ClothingBackpackBrigmedicFilled
  components:
  - type: StorageFill
    contents:
      - id: BoxSurvivalBrigmedic
      - id: Flash

# - type: startingGear
  # id: BrigmedicGear
  # equipment:
    # jumpsuit: ClothingUniformJumpsuitBrigmedic
    # outerClothing: ClothingOuterCoatAMG
    # back: ClothingBackpackBrigmedicFilled
    # shoes: ClothingShoesColorRed
    # gloves: ClothingHandsGlovesNitrile
    # eyes: ClothingEyesHudMedical
    # head: ClothingHeadHatBeretBrigmedic
    # id: BrigmedicPDA
    # ears: ClothingHeadsetBrigmedic
    # mask: ClothingMaskBreathMedicalSecurity
    # belt: ClothingBeltMedicalFilled
  # innerclothingskirt: ClothingUniformJumpskirtBrigmedic
  # satchel: ClothingBackpackSatchelBrigmedicFilled
  # duffelbag: ClothingBackpackDuffelBrigmedicFilled
