- type: job
  id: Rifleman
  name: job-name-rifleman
  description: job-description-rifleman
  playTimeTracker: jobrifleman
  requirements:
    - !type:DepartmentTimeRequirement
      department: Marine
      time: 36000 #10 hrs
  startingGear: SecurityOfficerGear2
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-squadleader
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External

- type: startingGear
  id: SecurityOfficerGear2
  equipment:
    jumpsuit: ClothingUniformJumpsuitSec
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHelmetBasic
    outerClothing: ClothingOuterArmorBasic
    id: SecurityPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolMk58Nonlethal
  innerclothingskirt: ClothingUniformJumpskirtSec
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
