- type: job
  id: squadleader
  name: job-name-squadleader
  description: job-description-squadleader
  playTimeTracker: jobsquadleader
  requirements:
    - !type:DepartmentTimeRequirement
      department: Marine
      time: 36000 #10 hrs
    - !type:RoleTimeRequirement
      role: JobAtmosphericTechnician # replace this with fireteam leader
      time: 10800 #3 hrs
  startingGear: SecurityOfficerGear3
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-command
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External

- type: startingGear
  id: SecurityOfficerGear3
  equipment:
    jumpsuit: ClothingUniformJumpsuitSec
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHelmetBasic
    outerClothing: ClothingOuterArmorBasic
    id: SecurityPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolMk58Nonlethal
  innerclothingskirt: ClothingUniformJumpskirtSec
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
