- type: job
  parent: CMJobXenoBase
  id: CMXenoSelectableXeno
  name: cm-job-name-selectable-xenonid
  playTimeTracker: CMJobSelectableXeno
  hidden: false
  jobEntity: CMXenoLarva

- type: playTimeTracker
  id: CMJobSelectableXeno
  isXeno: true
