- type: department
  parent: CMDepartmentBase
  id: CMEngineering
  name: cm-department-Engineering
  description: cm-department-Engineering-description
  color: "#A66300"
  roles:
  - CMChiefEngineer
  - CMOrdnanceTech
  - CMMaintTech
