- type: job
  parent: CMSurvivor
  id: RMCMedicalSurvivor
  name: cm-job-name-survivor # make new job name
  description: cm-job-description-survivor
  startingGear: RMCGearSurvivorDoctor
  accessGroups:
  - ColonistMedical
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillMedical: 3
        RMCSkillSurgery: 2
    - type: EquipSurvivorPreset
      preset: RMCSurvivorPresetMedical

﻿- type: startingGear
  id: RMCGearSurvivorDoctor #Port Outer clothing: Labcoat, 15 bio armor
  equipment:
    head: CMHeadCapSurgBlue
    mask: CMMaskSterile
    jumpsuit: CMJumpsuitLiaisonBlue 
    back: CMSatchelMedical
    gloves: CMHandsLatex
    shoes: RMCShoesLaceup
    id: CMIDCardColonist 
    eyes: RMCGlassesMedicalHUDGlasses
    ears: CMHeadsetColony
    pocket1: RMCM5Bayonet
    pocket2: RMCFlashlight

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSurvivorDoctor
  name: survivor doctor spawn point
  components:
  - type: SpawnPoint
    job_id: CMSurvivor
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: survivor
