- type: startingGear
  id: RMCGearSurvivorDoctor #Port Outer clothing: Labcoat, 15 bio armor
  equipment:
    head: CMHeadCapSurgBlue
    mask: CMMaskSterile
    jumpsuit: CMJumpsuitLiaisonBlue # TODO RMC14 /obj/item/clothing/under/rank/medical
    back: CMSatchelMedical
    gloves: CMHandsLatex
    shoes: RMCShoesLaceup
    id: CMIDCardColonist #Replace me with an ID with med access
    eyes: RMCGlassesMedicalHUDGlasses
    ears: CMHeadsetColony
    pocket1: RMCM5Bayonet
    pocket2: RMCFlashlightPen

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSurvivorDoctor
  name: survivor doctor spawn point
  components:
  - type: SpawnPoint
    job_id: CMSurvivor
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: survivor
