- type: job
  parent: CMSurvivor
  id: RMCMedicalSurvivor
  name: cm-job-name-survivor #make new name
  description: cm-job-description-survivor # Make new description
  startingGear: RMCGearSurvivor
  accessGroups:
  - ColonistEngi
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillConstruction: 3
        RMCSkillEngineer: 3
    - type: EquipSurvivorPreset
      preset: # RMCSurvivorPresetEngineer
 
 - type: startingGear
  id: RMCGearSurvivorEngineer
  equipment:
    head: ClothingHeadHatBeretEngineering
    gloves: CMHandsInsulated
    jumpsuit: ClothingUniformJumpsuitEngineering
    back: CMSatchelEngineer
    shoes: ClothingShoesColorOrange
    id: CMIDCardColonist
    ears: CMHeadsetColony
    pocket1: RMCM5Bayonet
    pocket2: RMCFlashlight

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSurvivorEngineer
  name: survivor engineer spawn point
  components:
  - type: SpawnPoint
    job_id: CMSurvivor
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: survivor
