- type: startingGear
  id: RMCGearColonistSecurity
  equipment:
    head: CMHeadBeretRed
    jumpsuit: CMJumpsuitColonist # /obj/item/clothing/under/rank/security
    back: CMSatchelSecurity
    shoes: CMBootsBlack # jackboots
    id: CMIDCardColonist
    ears: CMHeadsetColony
    pocket1: RMCM5Bayonet
    pocket2: RMCFlashlight

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointColonistSecurity
  name: colonist spawn point
  components:
  - type: SpawnPoint
    job_id: RMCColonist
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: survivor
