- type: job
  parent: CMSurvivor
  id: RMCSecuritySurvivor
  name: cm-job-name-survivor #make new name
  description: cm-job-description-survivor # Make new description
  startingGear: RMCGearSurvivorSecurity
  accessGroups:
  - ColonistSec
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillPolice: 2
        RMCSkillCqc: 2
    - type: EquipSurvivorPreset
      preset: RMCSurvivorPresetSecurity

﻿- type: startingGear
  id: RMCGearSurvivorSecurity
  equipment:
    head: CMHeadBeretRed
    eyes: CMGlassesSecurity
    jumpsuit: ClothingUniformJumpsuitSec 
    back: CMSatchelSecurity
    shoes: RMCShoesJackboots
    id: CMIDCardColonist # Marshalls actually get a badge looking thang
    ears: CMHeadsetColony
    pocket1: RMCM5Bayonet
    pocket2: RMCFlashlight

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSurvivorSecurity
  name: survivor security spawn point
  components:
  - type: SpawnPoint
    job_id: CMSurvivor
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: survivor
