- type: entity
  parent: MarkerBase
  id: RMCSpawnerCorpse
  name: Corpse Spawner - Unknown
  suffix: RMC
  components:
  - type: sprite
    sprite: _RMC14/Markers/landmarks.rsi
    layers:
    - state: corpse_spawner
  - type: ConditionalSpawner
    prototypes:
      - SalvageHumanCorpse
