- type: job
  id: HospitalCorpsman
  parent: JobBaseCM
  name: job-name-hospital-corpsman
  description: job-description-hospital-corpsman
  playTimeTracker: JobHospitalCorpsman
  requirements:
    - !type:DepartmentTimeRequirement
      department: Marine
      time: 3600 #1 hrs
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 3600 #1 hrs
  startingGear: HospitalCorpsmanGear
  icon: "JobIconHospitalCorpsman"
  supervisors: job-supervisors-squad-leader
  canBeAntag: false
  accessGroups:
  - HospitalCorpsman

# TODO cm14 Remove this later
- type: entity
  noSpawn: true
  parent: [ClothingBackpackBrigmedic, CMEntityBase]
  id: ClothingBackpackBrigmedicFilled
  components:
  - type: StorageFill
    contents:
      - id: BoxSurvivalHospitalCorpsman
      - id: Flash

- type: startingGear
  id: HospitalCorpsmanGear
  equipment:
    jumpsuit: CMJumpsuitMarineMedic
    back: ClothingBackpackBrigmedicFilled
    shoes: CMShoesCombatBoots
    gloves: CMHandsBlack
    eyes: ClothingEyesHudMedical
    head: CMArmorHelmetM10Medic
    outerClothing: ArmorMarineM3
    id: DogtagHospitalCorpsman
    ears: CMHeadsetAlphaMedic
    belt: ClothingBeltMedicalFilled
  satchel: ClothingBackpackSatchelBrigmedicFilled

- type: entity
  name: survival box
  parent: [BoxCardboard, CMEntityBase]
  id: BoxSurvivalHospitalCorpsman
  description: It's a box with basic internals inside.
  suffix: MedSec
  components:
  - type: StorageFill
    contents:
    - id: ClothingMaskBreathMedicalSecurity
    - id: EmergencyOxygenTankFilled
    - id: SpaceMedipen
    - id: EmergencyMedipen
    - id: EmergencyMedipen
    - id: FoodTinMRE
  - type: Sprite
    layers:
    - state: internals
    - state: emergencytank

- type: entity
  id: SpawnPointHospitalCorpsman
  parent: CMSpawnPointJobBase
  name: hospital corpsman spawn point
  components:
  - type: SpawnPoint
    job_id: HospitalCorpsman
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: hospital_corpsman
