- type: job
  parent: CMJobSquadBase
  id: CMHospitalCorpsman
  name: cm-job-name-hospital-corpsman
  description: cm-job-description-hospital-corpsman
  playTimeTracker: CMJobHospitalCorpsman
  requirements:
  - !type:TotalJobsTimeRequirement
    group: CMJobsMedical
    time: 3600 # 1 hours
  - !type:DepartmentTimeRequirement
    department: CMMarine
    time: 3600 # 1 hour
  startingGear: CMGearHospitalCorpsman
  icon: "CMJobIconHospitalCorpsman"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-sl
  canBeAntag: false
  accessGroups:
  - HospitalCorpsman
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      jtac: 1
      medical: 2
      surgery: 1

- type: startingGear
  id: CMGearHospitalCorpsman
  equipment:
    back: CMSatchelMarineMedic
    id: CMDogtagHospitalCorpsman

- type: startingGear
  id: CMGearHospitalCorpsmanEquipped
  equipment:
    jumpsuit: CMJumpsuitMarineMedic
    back: CMSatchelMarineMedic
    shoes: CMBootsBlackFilled
    gloves: CMHandsBlack
    eyes: ClothingEyesHudMedical
    head: CMArmorHelmetM10Medic
    outerClothing: CMArmorM3Medium
    id: CMDogtagHospitalCorpsman
    ears: CMHeadsetAlphaMedic
    belt: CMBeltMedicBagFilled

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointHospitalCorpsman
  name: hospital corpsman spawn point
  components:
  - type: SpawnPoint
    job_id: CMHospitalCorpsman
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: hospital_corpsman

- type: playTimeTracker
  id: CMJobHospitalCorpsman

