- type: job
  id: Rifleman
  parent: JobBaseCM
  name: job-name-rifleman
  description: job-description-rifleman
  playTimeTracker: JobRifleman
  startingGear: RiflemanGear
  icon: "JobIconRifleman"
  supervisors: job-supervisors-squad-leader
  canBeAntag: false
  #access:
  #Prep

- type: startingGear
  id: RiflemanGear
  equipment:
    jumpsuit: JumpsuitMarine
    back: ClothingBackpackSecurityFilled
    shoes: CMShoesCombatBoots
    head: ArmorHelmetM10
    outerClothing: ArmorMarineM3
    gloves: CMHandsBlack
    id: DogtagRifleman
    ears: ClothingHeadsetSecurity
  innerClothingSkirt: JumpsuitMarine
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled

- type: entity
  id: SpawnPointRifleman
  parent: CMSpawnPointJobBase
  name: rifleman spawn point
  components:
  - type: SpawnPoint
    job_id: Rifleman
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: rifleman
