- type: job
  id: SquadLeader
  parent: JobBaseCM
  name: job-name-squad-leader
  description: job-description-squad-leader
  playTimeTracker: JobSquadLeader
  requirements:
    - !type:DepartmentTimeRequirement
      department: Marine
      time: 36000 #10 hrs
    - !type:RoleTimeRequirement
      role: JobFireteamLeader
      time: 10800 #3 hrs
  startingGear: SquadLeaderGear
  icon: "JobIconSquadLeader"
  supervisors: job-supervisors-command
  canBeAntag: false
  #access:
  # Prep
  # Leader
  # Dropship

- type: startingGear
  id: SquadLeaderGear
  equipment:
    jumpsuit: CMJumpsuitMarineRTO
    back: ClothingBackpackSecurityFilled
    shoes: CMShoesCombatBoots
    head: CMArmorHelmetM11
    outerClothing: ArmorMarineM3
    gloves: CMHandsBlack
    id: DogtagSquadLeader
    ears: ClothingHeadsetSecurity
  innerClothingSkirt: CMJumpsuitMarineRTO
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled

- type: entity
  id: SpawnPointSquadLeader
  parent: CMSpawnPointJobBase
  name: squad leader spawn point
  components:
  - type: SpawnPoint
    job_id: SquadLeader
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: squad_leader
