- type: job
  id: WeaponsSpecialist
  parent: JobBaseCM
  name: job-name-weapons-specialist
  description: job-description-weapons-specialist
  playTimeTracker: JobWeaponsSpecialist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Marine
      time: 18000 #5 hrs
  startingGear: WeaponsSpecialistGear
  icon: "JobIconWeaponsSpecialist"
  supervisors: job-supervisors-squad-leader
  canBeAntag: false
  #accessGroups:
  # Prep

- type: startingGear
  id: WeaponsSpecialistGear
  equipment:
    jumpsuit: JumpsuitMarine
    back: ClothingBackpackSecurityFilled
    shoes: CMShoesCombatBoots
    head: ArmorHelmetM10
    outerClothing: ArmorMarineM3
    gloves: CMHandsBlack
    id: DogtagWeaponsSpecialist
    ears: CMHeadsetAlpha
  satchel: ClothingBackpackSatchelSecurityFilled

- type: entity
  id: SpawnPointWeaponsSpecialist
  parent: CMSpawnPointJobBase
  name: weapons specialist spawn point
  components:
  - type: SpawnPoint
    job_id: WeaponsSpecialist
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: weapons_specialist
