- type: job
  id: Rifleman
  parent: JobBaseCM
  name: job-name-rifleman
  description: job-description-rifleman
  playTimeTracker: JobRifleman
  startingGear: RiflemanGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-squad-leader
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External

- type: startingGear
  id: RiflemanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSec
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHelmetBasic
    outerClothing: ClothingOuterArmorBasic
    id: CMIDCardStandardDogtag
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolMk58Nonlethal
  innerClothingSkirt: ClothingUniformJumpskirtSec
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled

- type: entity
  id: SpawnPointRifleman
  parent: CMSpawnPointJobBase
  name: rifleman spawn point
  components:
  - type: SpawnPoint
    job_id: Rifleman
  - type: Sprite
    layers:
    - state: green
    - state: rifleman
