- type: job
  id: SquadLeader
  name: job-name-squad-leader
  description: job-description-squad-leader
  playTimeTracker: JobSquadLeader
  requirements:
    - !type:DepartmentTimeRequirement
      department: Marine
      time: 36000 #10 hrs
    - !type:RoleTimeRequirement
      role: JobFireteamLeader
      time: 10800 #3 hrs
  startingGear: SquadLeaderGear
  icon: "JobIconCaptain"
  supervisors: job-supervisors-command
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External

- type: startingGear
  id: SquadLeaderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSec
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHelmetBasic
    outerClothing: ClothingOuterArmorBasic
#    id: SecurityPDA TODO CM14
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolMk58Nonlethal
  innerClothingSkirt: ClothingUniformJumpskirtSec
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
