- type: job
  id: WeaponsSpecialist
  parent: JobBaseCM
  name: job-name-weapons-specialist
  description: job-description-weapons-specialist
  playTimeTracker: JobWeaponsSpecialist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Marine
      time: 18000 #5 hrs
  startingGear: WeaponsSpecialistGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-squad-leader
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External

- type: startingGear
  id: WeaponsSpecialistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSec
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHelmetBasic
    outerClothing: ClothingOuterArmorBasic
    id: SecurityPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolMk58Nonlethal
  innerClothingSkirt: ClothingUniformJumpskirtSec
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
