- type: entity
  id: CMAutolatheMachineCircuitboard
  parent: CMBaseMachineCircuitboard
  name: autolathe machine board
  description: A machine printed circuit board for an autolathe
  components:
    - type: MachineBoard
      prototype: Autolathe
      requirements:
        MatterBin: 3
        Manipulator: 1
      materialRequirements:
        Glass: 1

- type: entity
  id: CMPortableGeneratorPacmanMachineCircuitboard
  parent: CMBaseMachineCircuitboard
  name: P.A.C.M.A.N.-type portable generator machine board
  components:
    - type: Sprite
      state: power_mod
    - type: MachineBoard
      prototype: PortableGeneratorPacman
      requirements:
        Capacitor: 1
      materialRequirements:
        CableHV: 5
    - type: PhysicalComposition
      materialComposition:
        Glass: 200
      chemicalComposition:
        Silicon: 20
    - type: StaticPrice
      price: 40

- type: entity
  id: CMPortableGeneratorSuperPacmanMachineCircuitboard
  parent: CMBaseMachineCircuitboard
  name: S.U.P.E.R.P.A.C.M.A.N.-type portable generator machine board
  components:
    - type: Sprite
      state: power_mod
    - type: MachineBoard
      prototype: PortableGeneratorSuperPacman
      requirements:
        Capacitor: 2
      materialRequirements:
        CableHV: 10
    - type: PhysicalComposition
      materialComposition:
        Glass: 200
      chemicalComposition:
        Silicon: 20
    - type: StaticPrice
      price: 40
