# - type: department
  # id: Cargo
  # description: department-Cargo-description
  # color: "#A46106"


# - type: department
  # id: Civilian
  # description: department-Civilian-description
  # color: "#9FED58"


# - type: department
  # id: Command
  # description: department-Command-description
  # color: "#334E6D"


# - type: department
  # id: Engineering
  # description: department-Engineering-description
  # color: "#EFB341"


# - type: department
  # id: Medical
  # description: department-Medical-description
  # color: "#52B4E9"


# - type: department
  # id: Security
  # description: department-Security-description
  # color: "#DE3A3A"


# - type: department
  # id: Science
  # description: department-Science-description
  # color: "#D381C9"


# - type: department
  # id: Specific
  # description: department-Specific-description
  # color: "#9FED58"
  
- type: department
  id: marine
  description: department-marine-description
  color: "#DE3A3A"
  roles:
  - rifleman
  - squadleader
  - fireteamleader
  - weaponsspecialist
  - smartgunner
  - hospitalcorpsman
  - combattech
  

