# - type: department
  # id: Cargo
  # description: department-Cargo-description
  # color: "#A46106"


# - type: department
  # id: Civilian
  # description: department-Civilian-description
  # color: "#9FED58"


# - type: department
  # id: Command
  # description: department-Command-description
  # color: "#334E6D"


# - type: department
  # id: Engineering
  # description: department-Engineering-description
  # color: "#EFB341"


# - type: department
  # id: Medical
  # description: department-Medical-description
  # color: "#52B4E9"


# - type: department
  # id: Security
  # description: department-Security-description
  # color: "#DE3A3A"


# - type: department
  # id: Science
  # description: department-Science-description
  # color: "#D381C9"


# - type: department
  # id: Specific
  # description: department-Specific-description
  # color: "#9FED58"
  
- type: department
  id: marine
  description: department-marine-description
  color: "#DE3A3A"
  roles:
  # - rifleman
  # - squadleader
  # - fireteamleader
  # - weaponsspecialist
  # - smartgunner
  # - hospitalcorpsman
  # - combattech
  - alpharifleman
  - alphasquadleader
  - alphafireteamleader
  - alphaweaponsspecialist
  - alphasmartgunner
  - alphahospitalcorpsman
  - alphacombattech
  - bravorifleman
  - bravosquadleader
  - bravofireteamleader
  - bravoweaponsspecialist
  - bravosmartgunner
  - bravohospitalcorpsman
  - bravocombattech
  - charlierifleman
  - charliesquadleader
  - charliefireteamleader
  - charlieweaponsspecialist
  - charliesmartgunner
  - charliehospitalcorpsman
  - charliecombattech
  - deltarifleman
  - deltasquadleader
  - deltafireteamleader
  - deltaweaponsspecialist
  - deltasmartgunner
  - deltahospitalcorpsman
  - deltacombattech
  
- type: department
  id: marine-alpha
  description: department-marine-description
  color: "#DE3A3A"
  roles:
  - alpharifleman
  - alphasquadleader
  - alphafireteamleader
  - alphaweaponsspecialist
  - alphasmartgunner
  - alphahospitalcorpsman
  - alphacombattech
  
- type: department
  id: marine-bravo
  description: department-marine-description
  color: "#A46106"
  roles:
  - bravorifleman
  - bravosquadleader
  - bravofireteamleader
  - bravoweaponsspecialist
  - bravosmartgunner
  - bravohospitalcorpsman
  - bravocombattech
  
- type: department
  id: marine-charlie
  description: department-marine-description
  color: "#D381C9"
  roles:
  - charlierifleman
  - charliesquadleader
  - charliefireteamleader
  - charlieweaponsspecialist
  - charliesmartgunner
  - charliehospitalcorpsman
  - charliecombattech
  
- type: department
  id: marine-delta
  description: department-marine-description
  color: "#334E6D"
  roles:
  - deltarifleman
  - deltasquadleader
  - deltafireteamleader
  - deltaweaponsspecialist
  - deltasmartgunner
  - deltahospitalcorpsman
  - deltacombattech
  

