- type: job
  id: Survivor
  parent: JobBaseCM
  name: job-name-survivor
  description: job-description-survivor
  playTimeTracker: JobSurvivor
  requirements:
  - !type:RoleTimeRequirement
    role: Rifleman
    time: 18000 #5 hours
  - !type:RoleTimeRequirement
    role: HospitalCorpsman
    time: 18000 #5 hours
  - !type:RoleTimeRequirement
    role: CombatTech
    time: 18000 #5 hours
  startingGear: SurvivorGear
  icon: "JobIconSurvivor"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: job-supervisors-command # no one probably?
  canBeAntag: false

- type: startingGear
  id: SurvivorGear
  equipment:
    jumpsuit: CMJumpsuitColonist
    back: ClothingBackpackFilled
    shoes: CMShoesCombatBootsBrown
    ears: ClothingHeadsetGrey
  innerClothingSkirt: CMJumpsuitColonist
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled

- type: entity
  id: CMSpawnPointSurvivor
  parent: CMSpawnPointJobBase
  name: survivor spawn point
  components:
  - type: SpawnPoint
    job_id: Survivor
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: survivor
