- type: rank
  parent: RMCBaseRankSergeant
  id: RMCRankWeaponsSpecialistSergeant
  requirements:
  - !type:RoleTimeRequirement
    role: CMJobWeaponsSpecialist
    time: 252000 # 70 hours

- type: rank
  parent: RMCBaseRankLanceCorporal
  id: RMCRankWeaponsSpecialistCorporal
  requirements:
  - !type:RoleTimeRequirement
    role: CMJobWeaponsSpecialist
    time: 36000 # 10 hours