- type: job
  abstract: true
  id: CMJobBase
  isCM: true
  canBeAntag: false

- type: job
  abstract: true
  parent: CMJobBase
  id: CMJobSquadBase
  hasSquad: true

- type: department
  abstract: true
  id: CMDepartmentBase
  isCM: true

# Xeno
- type: job
  abstract: true
  parent: CMJobBase
  id: CMJobXenoBase
  description: null
  joinNotifyCrew: false
  icon: "CMJobIconEmpty"
  supervisors: cm-job-supervisors-queen
  accessGroups:
  - CMAccessXeno
  hasIcon: false
  hidden: true
