- type: entity
  parent: CMMobHuman
  id: RMCHumanCorpse
  save: false
  name: unidentified corpse
  description: I think they're dead.
  suffix: Dead
  components:
  - type: RandomHumanoidAppearance
    randomizeName: false
  - type: Damageable
    damage:
      types:
        Bloodloss: 36
        Asphyxiation: 44
        Slash: 77
        Blunt: 43
