- type: department
  parent: CMDepartmentBase
  id: CMSquad
  name: department-CMSquad
  description: cm-department-Marine-description
  color: "#01B5EE"
  roles:
  - CMRifleman
  - CMSquadLeader
  - CMFireteamLeader
  - CMWeaponsSpecialist
  - CMSmartGunOperator
  - CMHospitalCorpsman
  - CMCombatTech
