- type: rank
  id: RMCRankWeYaExecutiveSpecialist
  name: Executive Specialist
  shortenedName: Exec. Spc.
  requirements:
  - !type:RoleTimeRequirement
    role: CMJobLiaison
    time: 630000 # 175 hours

- type: rank
  id: RMCRankWeYaSeniorExecutive
  name: Senior Executive
  shortenedName: Sr. Exec.
  requirements:
  - !type:RoleTimeRequirement
    role: CMJobLiaison
    time: 252000 # 70 hours

- type: rank
  id: RMCRankWeYaExecutive
  name: Executive
  shortenedName: Exec.
  requirements:
  - !type:RoleTimeRequirement
    role: CMJobLiaison
    time: 90000 # 25 hours

- type: rank
  id: RMCRankWeYaJuniorExecutive
  name: Junior Executive
  shortenedName: Jr. Exec.